### ISSUE TITLE
Diagramme de classe

### ISSUE THREAD

**Issue by simonco** [GLAF2014/Multipoly#1]
J'ai (enfin) ajouté un premier jet pour le diagramme de classe. Le fichier xml peut être lu sur www.draw.io (une fois sur le site : menu fichier -> Import from -> Url -> https://raw.githubusercontent.com/GLAF2014/Multipoly/master/Diagrammes-de-classe/diagrammeJeu.xml  )

Les classes "entité" (Joueur, Propriété et Terrain) sont bien séparées des classes gestionnaires (Jeu et les différentes Case-) par des associations unidirectionnelles.
Mais j'hésite sur la direction de l'association entre les classes "Propriété" et "Joueur". 

Il n'y a pas toutes les méthodes, mais normalement les principales sont là.

**Comment by 399man** [comment]
Extra, merci.
